#pragma once

#define cJSON_Version appearance_cJSON_Version
#define cJSON_InitHooks appearance_cJSON_InitHooks
#define cJSON_Parse appearance_cJSON_Parse
#define cJSON_ParseWithLength appearance_cJSON_ParseWithLength
#define cJSON_ParseWithOpts appearance_cJSON_ParseWithOpts
#define cJSON_ParseWithLengthOpts appearance_cJSON_ParseWithLengthOpts
#define cJSON_Print appearance_cJSON_Print
#define cJSON_PrintUnformatted appearance_cJSON_PrintUnformatted
#define cJSON_PrintBuffered appearance_cJSON_PrintBuffered
#define cJSON_PrintPreallocated appearance_cJSON_PrintPreallocated
#define cJSON_Delete appearance_cJSON_Delete
#define cJSON_GetArraySize appearance_cJSON_GetArraySize
#define cJSON_GetArrayItem appearance_cJSON_GetArrayItem
#define cJSON_GetObjectItem appearance_cJSON_GetObjectItem
#define cJSON_GetObjectItemCaseSensitive appearance_cJSON_GetObjectItemCaseSensitive
#define cJSON_HasObjectItem appearance_cJSON_HasObjectItem
#define cJSON_GetErrorPtr appearance_cJSON_GetErrorPtr
#define cJSON_GetStringValue appearance_cJSON_GetStringValue
#define cJSON_GetNumberValue appearance_cJSON_GetNumberValue
#define cJSON_IsInvalid appearance_cJSON_IsInvalid
#define cJSON_IsFalse appearance_cJSON_IsFalse
#define cJSON_IsTrue appearance_cJSON_IsTrue
#define cJSON_IsBool appearance_cJSON_IsBool
#define cJSON_IsNull appearance_cJSON_IsNull
#define cJSON_IsNumber appearance_cJSON_IsNumber
#define cJSON_IsString appearance_cJSON_IsString
#define cJSON_IsArray appearance_cJSON_IsArray
#define cJSON_IsObject appearance_cJSON_IsObject
#define cJSON_IsRaw appearance_cJSON_IsRaw
#define cJSON_CreateNull appearance_cJSON_CreateNull
#define cJSON_CreateTrue appearance_cJSON_CreateTrue
#define cJSON_CreateFalse appearance_cJSON_CreateFalse
#define cJSON_CreateBool appearance_cJSON_CreateBool
#define cJSON_CreateNumber appearance_cJSON_CreateNumber
#define cJSON_CreateString appearance_cJSON_CreateString
#define cJSON_CreateRaw appearance_cJSON_CreateRaw
#define cJSON_CreateArray appearance_cJSON_CreateArray
#define cJSON_CreateObject appearance_cJSON_CreateObject
#define cJSON_CreateStringReference appearance_cJSON_CreateStringReference
#define cJSON_CreateObjectReference appearance_cJSON_CreateObjectReference
#define cJSON_CreateArrayReference appearance_cJSON_CreateArrayReference
#define cJSON_CreateIntArray appearance_cJSON_CreateIntArray
#define cJSON_CreateFloatArray appearance_cJSON_CreateFloatArray
#define cJSON_CreateDoubleArray appearance_cJSON_CreateDoubleArray
#define cJSON_CreateStringArray appearance_cJSON_CreateStringArray
#define cJSON_AddItemToArray appearance_cJSON_AddItemToArray
#define cJSON_AddItemToObject appearance_cJSON_AddItemToObject
#define cJSON_AddItemToObjectCS appearance_cJSON_AddItemToObjectCS
#define cJSON_AddItemReferenceToArray appearance_cJSON_AddItemReferenceToArray
#define cJSON_AddItemReferenceToObject appearance_cJSON_AddItemReferenceToObject
#define cJSON_DetachItemViaPointer appearance_cJSON_DetachItemViaPointer
#define cJSON_DetachItemFromArray appearance_cJSON_DetachItemFromArray
#define cJSON_DeleteItemFromArray appearance_cJSON_DeleteItemFromArray
#define cJSON_DetachItemFromObject appearance_cJSON_DetachItemFromObject
#define cJSON_DetachItemFromObjectCaseSensitive appearance_cJSON_DetachItemFromObjectCaseSensitive
#define cJSON_DeleteItemFromObject appearance_cJSON_DeleteItemFromObject
#define cJSON_DeleteItemFromObjectCaseSensitive appearance_cJSON_DeleteItemFromObjectCaseSensitive
#define cJSON_InsertItemInArray appearance_cJSON_InsertItemInArray
#define cJSON_ReplaceItemViaPointer appearance_cJSON_ReplaceItemViaPointer
#define cJSON_ReplaceItemInArray appearance_cJSON_ReplaceItemInArray
#define cJSON_ReplaceItemInObject appearance_cJSON_ReplaceItemInObject
#define cJSON_ReplaceItemInObjectCaseSensitive appearance_cJSON_ReplaceItemInObjectCaseSensitive
#define cJSON_Duplicate appearance_cJSON_Duplicate
#define cJSON_Duplicate_rec appearance_cJSON_Duplicate_rec
#define cJSON_Compare appearance_cJSON_Compare
#define cJSON_Minify appearance_cJSON_Minify
#define cJSON_AddNullToObject appearance_cJSON_AddNullToObject
#define cJSON_AddTrueToObject appearance_cJSON_AddTrueToObject
#define cJSON_AddFalseToObject appearance_cJSON_AddFalseToObject
#define cJSON_AddBoolToObject appearance_cJSON_AddBoolToObject
#define cJSON_AddNumberToObject appearance_cJSON_AddNumberToObject
#define cJSON_AddStringToObject appearance_cJSON_AddStringToObject
#define cJSON_AddRawToObject appearance_cJSON_AddRawToObject
#define cJSON_AddObjectToObject appearance_cJSON_AddObjectToObject
#define cJSON_AddArrayToObject appearance_cJSON_AddArrayToObject
#define cJSON_SetNumberHelper appearance_cJSON_SetNumberHelper
#define cJSON_SetValuestring appearance_cJSON_SetValuestring
#define cJSON_malloc appearance_cJSON_malloc
#define cJSON_free appearance_cJSON_free

#include <cJSON.h>

#ifdef __cplusplus
extern "C" {
#endif
void AppearanceJsonSetAllocator(void* (*allocate)(size_t), void (*release)(void*));
#ifdef __cplusplus
}
#endif
