set(SOURCES
    "main.cc"
    "settings.cc"
    "usb_msc_mode.cc"
    "rodakos_adapters/backlight_adapter.cc"
    "rodakos_adapters/wifi_adapter.cc"
    "rodakos_adapters/wifi_config.cc"
    "rodakos_adapters/file_service.cc"
    "phone_os/phone_app_registry.cc"
    "phone_os/phone_app_host.cc"
    "phone_os/phone_navigation.cc"
    "phone_os/phone_system.cc"
    "phone_os/audio_focus_service.cc"
    "phone_os/audio_output_service.cc"
    "phone_os/audio_service.cc"
    "phone_os/music_player_service.cc"
    "phone_os/light_service.cc"
    "phone_os/button_binding_service.cc"
    "phone_os/camera_service.cc"
    "phone_os/time_service.cc"
    "phone_os/voice_assistant_service.cc"
    "phone_os/voice_assistant_transport.cc"
    "phone_os/voice_recorder_service.cc"
    "phone_os/voice_wake_service.cc"
    "phone_os/device_cloud_config.cc"
    "phone_os/voice_cloud_websocket_transport.cc"
    "phone_os/web_file_system_service.cc"
    "phone_ui/phone_ui.cc"
    "phone_ui/phone_fonts.cc"
    "phone_ui/phone_theme.cc"
    "phone_ui/phone_screen.cc"
    "phone_ui/phone_components.cc"
    "phone_ui/rodakos_layout.cc"
    "phone_ui/rodakos_theme.cc"
    "phone_ui/soft_keyboard.cc"
    "phone_ui/image_library.cc"
    "phone_ui/jpg/jpeg_to_image.c"
    "apps/built_in_apps.cc"
    "apps/home/home_app.cc"
    "apps/settings/settings_app.cc"
    "apps/settings/settings_app_internal.cc"
    "apps/settings/settings_buttons_page.cc"
    "apps/settings/settings_datetime_page.cc"
    "apps/settings/settings_device_cloud_page.cc"
    "apps/settings/settings_main_page.cc"
    "apps/settings/settings_usb_disk.cc"
    "apps/settings/settings_web_files_page.cc"
    "apps/settings/settings_wifi_page.cc"
    "apps/photos/photos_app.cc"
    "apps/camera/camera_app.cc"
    "apps/clock/clock_app.cc"
    "apps/file_manager/file_manager_app.cc"
    "apps/music/music_app.cc"
    "apps/assistant/assistant_app.cc"
    "apps/system_info/system_info_app.cc"
    "apps/smart/smart_app.cc"
)

idf_component_register(
    SRCS ${SOURCES}
    INCLUDE_DIRS "." "rodakos_adapters" "phone_os" "phone_ui" "apps"
    REQUIRES
        lvgl
        esp_lvgl_port
        nvs_flash
        esp_wifi
        esp_http_server
        esp_http_client
        esp_netif
        lwip
        json
        esp_board_manager
        espressif__esp_websocket_client
        espressif__esp_codec_dev
        chmorgan__esp-libhelix-mp3
        app_update
        esp_app_format
        esp_timer
        heap
        led_strip
        spi_flash
        fatfs
        sdmmc
        esp_tinyusb
        esp_new_jpeg
)
