# AES belongs to the IDF 6.0.2 PSA crypto target, not the component wrapper.
if(NOT TARGET tfpsacrypto)
    message(FATAL_ERROR "Reviewed AES target tfpsacrypto is missing")
endif()
get_target_property(aes_target_type tfpsacrypto TYPE)
get_target_property(aes_target_imported tfpsacrypto IMPORTED)
get_target_property(aes_target_output tfpsacrypto OUTPUT_NAME)
if(NOT aes_target_type STREQUAL "STATIC_LIBRARY" OR aes_target_imported OR NOT aes_target_output STREQUAL "tfpsacrypto")
    message(FATAL_ERROR "Reviewed AES target identity differs")
endif()
idf_build_get_property(aes_cleanup_idf IDF_PATH)
idf_build_get_property(aes_cleanup_python PYTHON)
idf_build_get_property(aes_cleanup_chip IDF_TARGET)
if(NOT aes_cleanup_chip STREQUAL "esp32s3")
    message(FATAL_ERROR "AES cleanup overlay was reviewed only for ESP32-S3")
endif()
set(aes_cleanup_script "${PROJECT_DIR}/tools/prepare_aes_dma_cleanup_patch.py")
set(aes_cleanup_output "${CMAKE_BINARY_DIR}/rodak_patches/aes_dma_cleanup")
set(aes_cleanup_generated "${aes_cleanup_output}/esp_aes_dma_core.c")
set(aes_cleanup_original "${aes_cleanup_idf}/components/mbedtls/port/aes/dma/esp_aes_dma_core.c")
get_target_property(aes_cleanup_sources tfpsacrypto SOURCES)
get_target_property(aes_cleanup_source_dir tfpsacrypto SOURCE_DIR)
set(aes_cleanup_replacements 0)
set(aes_cleanup_new_sources "")
foreach(aes_source IN LISTS aes_cleanup_sources)
    get_filename_component(aes_source_absolute "${aes_source}" ABSOLUTE BASE_DIR "${aes_cleanup_source_dir}")
    if(aes_source_absolute STREQUAL aes_cleanup_original)
        list(APPEND aes_cleanup_new_sources "${aes_cleanup_generated}")
        math(EXPR aes_cleanup_replacements "${aes_cleanup_replacements} + 1")
    else()
        list(APPEND aes_cleanup_new_sources "${aes_source}")
    endif()
endforeach()
if(NOT aes_cleanup_replacements EQUAL 1)
    message(FATAL_ERROR "Expected exactly one reviewed AES DMA source in tfpsacrypto")
endif()
set(aes_cleanup_command "${aes_cleanup_python}" "${aes_cleanup_script}"
    --idf-path "${aes_cleanup_idf}" --output-dir "${aes_cleanup_output}")
execute_process(COMMAND ${aes_cleanup_command} --print-inputs
    RESULT_VARIABLE aes_cleanup_result OUTPUT_VARIABLE aes_cleanup_inputs ERROR_VARIABLE aes_cleanup_error
    OUTPUT_STRIP_TRAILING_WHITESPACE)
if(NOT aes_cleanup_result EQUAL 0)
    message(FATAL_ERROR "${aes_cleanup_inputs}${aes_cleanup_error}")
endif()
string(REPLACE "\r\n" "\n" aes_cleanup_inputs "${aes_cleanup_inputs}")
string(REPLACE "\n" ";" aes_cleanup_inputs "${aes_cleanup_inputs}")
set_property(DIRECTORY APPEND PROPERTY CMAKE_CONFIGURE_DEPENDS ${aes_cleanup_inputs})
execute_process(COMMAND ${aes_cleanup_command}
    RESULT_VARIABLE aes_cleanup_result OUTPUT_VARIABLE aes_cleanup_message ERROR_VARIABLE aes_cleanup_error)
if(NOT aes_cleanup_result EQUAL 0)
    message(FATAL_ERROR "${aes_cleanup_message}${aes_cleanup_error}")
endif()
string(STRIP "${aes_cleanup_message}" aes_cleanup_message)
message(STATUS "${aes_cleanup_message}")
add_custom_command(OUTPUT "${aes_cleanup_generated}" COMMAND ${aes_cleanup_command}
    DEPENDS ${aes_cleanup_inputs} VERBATIM)
add_custom_target(rodak_aes_dma_cleanup_overlay DEPENDS "${aes_cleanup_generated}")
set_property(TARGET tfpsacrypto PROPERTY SOURCES "${aes_cleanup_new_sources}")
add_dependencies(tfpsacrypto rodak_aes_dma_cleanup_overlay)
