idf_component_get_property(dvp_rcc_dir esp_driver_cam COMPONENT_DIR)
idf_component_get_property(dvp_rcc_lib esp_driver_cam COMPONENT_LIB)
idf_build_get_property(dvp_rcc_python PYTHON)
idf_build_get_property(dvp_rcc_idf IDF_PATH)
idf_build_get_property(dvp_rcc_chip IDF_TARGET)
if(NOT dvp_rcc_chip STREQUAL "esp32s3")
    message(FATAL_ERROR "DVP RCC overlay was reviewed only for ESP32-S3")
endif()
set(dvp_rcc_script "${PROJECT_DIR}/tools/prepare_dvp_rcc_patch.py")
set(dvp_rcc_output "${CMAKE_BINARY_DIR}/rodak_patches/dvp_rcc")
set(dvp_rcc_generated "${dvp_rcc_output}/esp_cam_ctlr_dvp_cam.c")
set(dvp_rcc_command "${dvp_rcc_python}" "${dvp_rcc_script}"
    --idf-path "${dvp_rcc_idf}" --output-dir "${dvp_rcc_output}")
execute_process(COMMAND ${dvp_rcc_command} --print-inputs
    RESULT_VARIABLE dvp_rcc_inputs_result OUTPUT_VARIABLE dvp_rcc_inputs_output
    ERROR_VARIABLE dvp_rcc_inputs_error OUTPUT_STRIP_TRAILING_WHITESPACE)
if(NOT dvp_rcc_inputs_result EQUAL 0)
    message(FATAL_ERROR "${dvp_rcc_inputs_output}${dvp_rcc_inputs_error}")
endif()
string(REPLACE "\r\n" "\n" dvp_rcc_inputs_output "${dvp_rcc_inputs_output}")
string(REPLACE "\n" ";" dvp_rcc_inputs "${dvp_rcc_inputs_output}")
set_property(DIRECTORY APPEND PROPERTY CMAKE_CONFIGURE_DEPENDS ${dvp_rcc_inputs})
execute_process(COMMAND ${dvp_rcc_command}
    RESULT_VARIABLE dvp_rcc_prepare_result OUTPUT_VARIABLE dvp_rcc_prepare_output
    ERROR_VARIABLE dvp_rcc_prepare_error)
if(NOT dvp_rcc_prepare_result EQUAL 0)
    message(FATAL_ERROR "${dvp_rcc_prepare_output}${dvp_rcc_prepare_error}")
endif()
string(STRIP "${dvp_rcc_prepare_output}" dvp_rcc_prepare_output)
message(STATUS "${dvp_rcc_prepare_output}")
add_custom_command(OUTPUT "${dvp_rcc_generated}" COMMAND ${dvp_rcc_command}
    DEPENDS ${dvp_rcc_inputs} VERBATIM)
add_custom_target(rodak_dvp_rcc_overlay DEPENDS "${dvp_rcc_generated}")
get_target_property(dvp_rcc_sources ${dvp_rcc_lib} SOURCES)
set(dvp_rcc_replacements 0)
set(dvp_rcc_new_sources "")
foreach(dvp_rcc_source IN LISTS dvp_rcc_sources)
    get_filename_component(dvp_rcc_absolute "${dvp_rcc_source}" ABSOLUTE BASE_DIR "${dvp_rcc_dir}")
    if(dvp_rcc_absolute STREQUAL "${dvp_rcc_dir}/dvp/src/esp_cam_ctlr_dvp_cam.c")
        list(APPEND dvp_rcc_new_sources "${dvp_rcc_generated}")
        math(EXPR dvp_rcc_replacements "${dvp_rcc_replacements} + 1")
    else()
        list(APPEND dvp_rcc_new_sources "${dvp_rcc_source}")
    endif()
endforeach()
if(NOT dvp_rcc_replacements EQUAL 1)
    message(FATAL_ERROR "Expected exactly one reviewed DVP controller source in ${dvp_rcc_lib}")
endif()
set_property(TARGET ${dvp_rcc_lib} PROPERTY SOURCES "${dvp_rcc_new_sources}")
add_dependencies(${dvp_rcc_lib} rodak_dvp_rcc_overlay)
