idf_component_get_property(dvp_cleanup_video_dir espressif__esp_video COMPONENT_DIR)
idf_component_get_property(dvp_cleanup_video_lib espressif__esp_video COMPONENT_LIB)
idf_build_get_property(dvp_cleanup_python PYTHON)
idf_build_get_property(dvp_cleanup_idf IDF_PATH)
idf_build_get_property(dvp_cleanup_chip IDF_TARGET)
if(NOT dvp_cleanup_chip STREQUAL "esp32s3")
    message(FATAL_ERROR "DVP cleanup overlay was reviewed only for ESP32-S3")
endif()
get_filename_component(dvp_cleanup_managed_dir "${dvp_cleanup_video_dir}" DIRECTORY)
set(dvp_cleanup_script "${PROJECT_DIR}/tools/prepare_dvp_deinit_patch.py")
set(dvp_cleanup_output "${CMAKE_BINARY_DIR}/rodak_patches/dvp_deinit")
set(dvp_cleanup_generated "${dvp_cleanup_output}/esp_video_init.c")
set(dvp_cleanup_command "${dvp_cleanup_python}" "${dvp_cleanup_script}"
    --managed-dir "${dvp_cleanup_managed_dir}" --output-dir "${dvp_cleanup_output}"
    --idf-path "${dvp_cleanup_idf}")
execute_process(COMMAND ${dvp_cleanup_command} --print-inputs
    RESULT_VARIABLE dvp_cleanup_result OUTPUT_VARIABLE dvp_cleanup_inputs ERROR_VARIABLE dvp_cleanup_error
    OUTPUT_STRIP_TRAILING_WHITESPACE)
if(NOT dvp_cleanup_result EQUAL 0)
    message(FATAL_ERROR "${dvp_cleanup_inputs}${dvp_cleanup_error}")
endif()
string(REPLACE "\r\n" "\n" dvp_cleanup_inputs "${dvp_cleanup_inputs}")
string(REPLACE "\n" ";" dvp_cleanup_inputs "${dvp_cleanup_inputs}")
set_property(DIRECTORY APPEND PROPERTY CMAKE_CONFIGURE_DEPENDS ${dvp_cleanup_inputs})
execute_process(COMMAND ${dvp_cleanup_command}
    RESULT_VARIABLE dvp_cleanup_result OUTPUT_VARIABLE dvp_cleanup_message ERROR_VARIABLE dvp_cleanup_error)
if(NOT dvp_cleanup_result EQUAL 0)
    message(FATAL_ERROR "${dvp_cleanup_message}${dvp_cleanup_error}")
endif()
string(STRIP "${dvp_cleanup_message}" dvp_cleanup_message)
message(STATUS "${dvp_cleanup_message}")
get_target_property(dvp_cleanup_sources ${dvp_cleanup_video_lib} SOURCES)
set(dvp_cleanup_replacements 0)
set(dvp_cleanup_new_sources "")
foreach(dvp_cleanup_source IN LISTS dvp_cleanup_sources)
    get_filename_component(dvp_cleanup_absolute "${dvp_cleanup_source}" ABSOLUTE BASE_DIR "${dvp_cleanup_video_dir}")
    if(dvp_cleanup_absolute STREQUAL "${dvp_cleanup_video_dir}/src/esp_video_init.c")
        list(APPEND dvp_cleanup_new_sources "${dvp_cleanup_generated}")
        math(EXPR dvp_cleanup_replacements "${dvp_cleanup_replacements} + 1")
    else()
        list(APPEND dvp_cleanup_new_sources "${dvp_cleanup_source}")
    endif()
endforeach()
if(NOT dvp_cleanup_replacements EQUAL 1)
    message(FATAL_ERROR "Expected exactly one reviewed ESP Video init source")
endif()
add_custom_command(OUTPUT "${dvp_cleanup_generated}" COMMAND ${dvp_cleanup_command}
    DEPENDS ${dvp_cleanup_inputs} VERBATIM)
add_custom_target(rodak_dvp_cleanup_overlay DEPENDS "${dvp_cleanup_generated}")
set_property(TARGET ${dvp_cleanup_video_lib} PROPERTY SOURCES "${dvp_cleanup_new_sources}")
add_dependencies(${dvp_cleanup_video_lib} rodak_dvp_cleanup_overlay)
