# Used by ESP-IDF and host LVGL targets so both compile the same checked source.
function(rodak_apply_lodepng_patch target component_dir rodak_root python)
    set(script "${rodak_root}/tools/prepare_lodepng_patch.py")
    set(provenance "${rodak_root}/patches/lvgl/9.3.0/provenance.json")
    set(original "${component_dir}/src/libs/lodepng/lodepng.c")
    set(generated "${CMAKE_BINARY_DIR}/rodak_patches/lvgl/lodepng.c")
    file(READ "${provenance}" provenance_json)
    string(JSON source_count LENGTH "${provenance_json}" source_hashes_lf)
    math(EXPR last_source "${source_count} - 1")
    set(inputs "${script}" "${provenance}" "${rodak_root}/dependencies.lock"
        "${rodak_root}/main/idf_component.yml" "${component_dir}/.component_hash")
    foreach(index RANGE ${last_source})
        string(JSON source MEMBER "${provenance_json}" source_hashes_lf ${index})
        list(APPEND inputs "${component_dir}/${source}")
    endforeach()
    set_property(DIRECTORY APPEND PROPERTY CMAKE_CONFIGURE_DEPENDS ${inputs})
    set(command "${python}" "${script}" --component-dir "${component_dir}"
        --lock-file "${rodak_root}/dependencies.lock"
        --project-manifest "${rodak_root}/main/idf_component.yml" --output "${generated}")
    execute_process(COMMAND ${command} RESULT_VARIABLE result OUTPUT_VARIABLE output ERROR_VARIABLE error)
    if(NOT result EQUAL 0)
        message(FATAL_ERROR "${output}${error}")
    endif()
    string(STRIP "${output}" output)
    message(STATUS "${output}")
    add_custom_command(OUTPUT "${generated}" COMMAND ${command} DEPENDS ${inputs} VERBATIM)
    add_custom_target(rodak_lodepng_overlay DEPENDS "${generated}")
    add_dependencies(${target} rodak_lodepng_overlay)
    get_target_property(sources ${target} SOURCES)
    set(replaced "")
    set(count 0)
    foreach(source IN LISTS sources)
        get_filename_component(absolute "${source}" ABSOLUTE BASE_DIR "${component_dir}")
        if(absolute STREQUAL original)
            list(APPEND replaced "${generated}")
            math(EXPR count "${count} + 1")
        else()
            list(APPEND replaced "${source}")
        endif()
    endforeach()
    if(NOT count EQUAL 1)
        message(FATAL_ERROR "Expected exactly one LodePNG source in LVGL target")
    endif()
    set_property(TARGET ${target} PROPERTY SOURCES "${replaced}")
    target_include_directories(${target} PRIVATE "${component_dir}/src/libs/lodepng")
endfunction()
